name: "Deployment"

on:
  push:
    branches:
      - master

jobs:
  lint_and_test:
    name: "Lint & Test"
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Login to NPM
        run: make npm-auth

      - name: Build lambdas
        run: make build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1

      - name: Lint code
        run: make lint

      - name: Install Jest
        run: npm i -g jest

      - name: Run test
        run: make test

      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #   threshold: 80 # optional parameter

  npm-packages:
    name: "Publishes npm packages to team NPM repostiroy"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Login to repo
        run: aws codeartifact login --tool npm --repository team-npm --domain moggies-io --domain-owner ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Publish npm packages
        run: make repo-publish

  deploy_lambdas:
    name: "Deploys lambdas to AWS"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Login to NPM
        run: make npm-auth

      - name: Build lambdas
        run: make build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1

      - name: Deploy domain_api
        run: FUN_NAME=domain_api make update-lambda-fn

      - name: Deploy loadtest_api
        run: FUN_NAME=loadtest_api make update-lambda-fn

      - name: Deploy metrics_api
        run: FUN_NAME=metrics_api make update-lambda-fn

      - name: Deploy organisation_api
        run: FUN_NAME=organisation_api make update-lambda-fn

      - name: Deploy playbook_api
        run: FUN_NAME=playbook_api make update-lambda-fn

      - name: Deploy user_api
        run: FUN_NAME=user_api make update-lambda-fn
